### ISSUE TITLE
No Build Folder on MacOS

### ISSUE THREAD

**Issue by dalebaldwin** [Fitbit/fitbit-sdk-toolchain#149]
Ran the CLI for the first time today and created a new project however when I try to run a build I fail to get a build folder. The CLI says it completes the build but no build folder is contained within the project and I can't find any builds located anywhere else on my machine. Any idea why this is happening and how to fix it?

**Comment by Hexxeh** [comment]
Appears that the offending package is https://github.com/mafintosh/end-of-stream/commit/ec0b5bd655cca50e9ab8ac51319badd0bc357a03

**Comment by Hexxeh** [comment]
Change that caused the break is https://github.com/mafintosh/end-of-stream/commit/25b242518f50571c3348cff11553712cbf832d04#diff-168726dbe96b3ce427e7fedce31bb0bcR47-R48

**Comment by Hexxeh** [comment]
This is now fixed by a new version of end-of-stream, if you're still having issues update your dependencies.
