### ISSUE TITLE
Feature Request: Mira: BT API

### ISSUE THREAD

**Issue by Heceldi** [Fitbit/fitbit-sdk-toolchain#151]
I've been looking over things, and not finding this anywhere. Versa 2 (Mira) supports BT. I can play audio over it using built-ins. I'm not find that functionality anywhere in the API, and would like to see it to develop a custom music player that doesn't rely on a phone being nearby or network access.

**Comment by Hexxeh** [comment]
Hey,

Please use the Fitbit Community for these sort of feature suggestions so we can collect them all in one place. This issue tracker is intended for purely toolchain related issues.

Link: https://community.fitbit.com/t5/Feature-Suggestions/idb-p/features/label-name/sdk

Thanks!
