### ISSUE TITLE
Versa 2 seems not to display gradient rectangles

### ISSUE THREAD

**Issue by gaperton** [Fitbit/fitbit-sdk-toolchain#154]
Many watch faces are broken in Versa 2 because `<gradientRect>` is not displayed on the device. The simulator works fine.

I guess this is hardly a problem of the SDK toolchain, but this repo is the closest thing to a public bug tracker for issues of that sort and this one is a high severity issue.

**Comment by Hexxeh** [comment]
This issue is being tracked internally for resolution via a future firmware update.

**Comment by Hexxeh** [comment]
Issue has been resolved and should be released with the next FW update.
