### ISSUE TITLE
Inbox files as iterable

### ISSUE THREAD

**Issue by SergioMorchon** [Fitbit/fitbit-sdk-toolchain#206]
# Inbox files as iterable
Actually, the way to read the inbox queue of file names is by manually looping over `inbox.nextFile()` until it returns nothing.

That's already solved with iterables.
Can you oevolve that API to expose something like this:
```typescript
const inboxFiles = {
	next: () => {
		const value = inbox.nextFile();
		return {
			value: value as string,
			done: !value,
		};
	},
	[Symbol.iterator]: function () {
		return this;
	},
};
```

So we can do stuff like
```typescript
for (const fileName of inboxFiles) {
	doStuff(fileName);
}
```
compared to:
```typescript
let fileName = inbox.nextFile();
while (fileName) {
	doStuff(fileName);
	fileName = inbox.nextFile(fileName);
}
```

**Comment by Hexxeh** [comment]
There's no native support on device for iterators as far as I know, they get transpiled down. Which means that native APIs can't be implemented in terms of them.

**Comment by SergioMorchon** [comment]
So do you think that we can keep this issue open until we have native iterators?
They're supported by [JerryScript 2](https://github.com/jerryscript-project/jerryscript/releases/tag/v2.0)

**Comment by Hexxeh** [comment]
We can keep it open if you like, but we don't typically do SDK roadmapping based on these issues, but using the feature suggestions forums (amongst other sources).

We're not using JerryScript 2 at this time.

**Comment by SergioMorchon** [comment]
Oh, understood. Sorry for the inconvenience, I'll post this as a forum suggestion
