### ISSUE TITLE
Can I build apps for Inspire/Inspire HR with this toolchain?

### ISSUE THREAD

**Issue by melissamcewen** [Fitbit/fitbit-sdk-toolchain#86]
Hi, I noticed my new Inspire HR has an "apps" tab and I was wondering if it's possible to develop apps for it? I looked at this SDK but I'm not sure if the same OS is used on the Inspires?

**Comment by orviwan** [comment]
Unfortunately, the SDK only supports devices running Fitbit OS (Ionic, Versa, and Versa Lite). Sorry.
